services:
  legal-va-2-backend-app:
    build:
      context: app
      dockerfile: Dockerfile
    image: harbor.cybertech.com.vn:8443/legal-va/backend-2
    env_file:
      - app/.env 
    ports:
      - "32213:80"
